hub:
    resource: "@HubBundle/Controller/"
    type:     annotation
    prefix:   /

auth:
    resource: "@AuthBundle/Controller/"
    type:     annotation
    prefix:   /

planner:
    resource: "@PlannerBundle/Controller/"
    type:     annotation
    prefix:   /

closet:
    resource: "@ClosetBundle/Controller/"
    type:     annotation
    prefix:   /

health:
    resource: "@HealthBundle/Controller/"
    type:     annotation
    prefix:   /
