health_meal_plan:
    resource: "@HealthBundle/Controller/MealPlanController.php"
    type:     annotation

health_meal:
    resource: "@HealthBundle/Controller/MealController.php"
    type:     annotation

health_food:
    resource: "@HealthBundle/Controller/FoodController.php"
    type:     annotation

hub:
    resource: "@HubBundle/Controller/"
    type:     annotation
    prefix:   /

auth:
    resource: "@AuthBundle/Controller/"
    type:     annotation
    prefix:   /

planner:
    resource: "@PlannerBundle/Controller/"
    type:     annotation
    prefix:   /

closet:
    resource: "@ClosetBundle/Controller/"
    type:     annotation
    prefix:   /

health:
    resource: "@HealthBundle/Controller/"
    type:     annotation
    prefix:   /
