<?php

namespace Ramity\HealthBundle\Repository;

/**
 * MealPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
